<template>
  <div>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
  </div>
</template>

<script>
export default {
  setup() {
    return {};
  },
};
</script>

<style lang="scss" scoped>
</style>